import Head from "next/head";
import Script from "next/script";
import React from "react";

export default function Home() {
  return (
    <div>
      <Head>
        <title> Next </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen bg-gradient-to-b from-gray-900 to-slate-800 flex flex-col text-white">

        <h1 className=" text-white text-8xl">Tarek</h1>




      </div>
    </div>
  );
}
